"""add zone area field area hierarchy

Revision ID: 78b9e616e615
Revises: 0531dde88880
Create Date: 2026-08-19 15:47:14.646182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b9e616e615'
down_revision: Union[str, Sequence[str], None] = '0531dde88880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_zone_code'), 'zones', ['zone_code'], unique=True)
    op.create_index(op.f('ix_zones_zone_name'), 'zones', ['zone_name'], unique=True)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.String(length=50), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_area_code'), 'areas', ['area_code'], unique=True)
    op.create_index(op.f('ix_areas_area_name'), 'areas', ['area_name'], unique=False)
    op.create_index(op.f('ix_areas_zone_id'), 'areas', ['zone_id'], unique=False)
    op.create_table('field_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_area_code', sa.String(length=50), nullable=False),
    sa.Column('field_area_name', sa.String(length=100), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_areas_area_id'), 'field_areas', ['area_id'], unique=False)
    op.create_index(op.f('ix_field_areas_field_area_code'), 'field_areas', ['field_area_code'], unique=True)
    op.create_index(op.f('ix_field_areas_field_area_name'), 'field_areas', ['field_area_name'], unique=False)
    op.add_column('officers', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.add_column('officers', sa.Column('area_id', sa.Integer(), nullable=True))
    op.add_column('officers', sa.Column('field_area_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_officers_area_id'), 'officers', ['area_id'], unique=False)
    op.create_index(op.f('ix_officers_field_area_id'), 'officers', ['field_area_id'], unique=False)
    op.create_index(op.f('ix_officers_zone_id'), 'officers', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'officers', 'field_areas', ['field_area_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'officers', 'zones', ['zone_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'officers', 'areas', ['area_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'officers', type_='foreignkey')
    op.drop_constraint(None, 'officers', type_='foreignkey')
    op.drop_constraint(None, 'officers', type_='foreignkey')
    op.drop_index(op.f('ix_officers_zone_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_field_area_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_area_id'), table_name='officers')
    op.drop_column('officers', 'field_area_id')
    op.drop_column('officers', 'area_id')
    op.drop_column('officers', 'zone_id')
    op.drop_index(op.f('ix_field_areas_field_area_name'), table_name='field_areas')
    op.drop_index(op.f('ix_field_areas_field_area_code'), table_name='field_areas')
    op.drop_index(op.f('ix_field_areas_area_id'), table_name='field_areas')
    op.drop_table('field_areas')
    op.drop_index(op.f('ix_areas_zone_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_code'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_zones_zone_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_zone_code'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
