"""add pending consumers

Revision ID: 9930249c84fe
Revises: 49ae286a3763
Create Date: 2026-08-17 17:32:33.016030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9930249c84fe'
down_revision: Union[str, Sequence[str], None] = '49ae286a3763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_consumers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.String(length=100), nullable=False),
    sa.Column('consumer_name', sa.String(length=200), nullable=False),
    sa.Column('meter_id', sa.String(length=100), nullable=False),
    sa.Column('pending_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('days_pending', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_consumers_consumer_id'), 'pending_consumers', ['consumer_id'], unique=True)
    op.create_index(op.f('ix_pending_consumers_consumer_name'), 'pending_consumers', ['consumer_name'], unique=False)
    op.create_index(op.f('ix_pending_consumers_meter_id'), 'pending_consumers', ['meter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_consumers_meter_id'), table_name='pending_consumers')
    op.drop_index(op.f('ix_pending_consumers_consumer_name'), table_name='pending_consumers')
    op.drop_index(op.f('ix_pending_consumers_consumer_id'), table_name='pending_consumers')
    op.drop_table('pending_consumers')
    # ### end Alembic commands ###
