"""add geographical scope to master meters

Revision ID: e65c39865725
Revises: 78b9e616e615
Create Date: 2026-08-19 17:18:20.826801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65c39865725'
down_revision: Union[str, Sequence[str], None] = '78b9e616e615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_meters', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.add_column('master_meters', sa.Column('area_id', sa.Integer(), nullable=True))
    op.add_column('master_meters', sa.Column('field_area_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_master_meters_area_id'), 'master_meters', ['area_id'], unique=False)
    op.create_index(op.f('ix_master_meters_field_area_id'), 'master_meters', ['field_area_id'], unique=False)
    op.create_index(op.f('ix_master_meters_zone_id'), 'master_meters', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'master_meters', 'areas', ['area_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'master_meters', 'zones', ['zone_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'master_meters', 'field_areas', ['field_area_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_meters', type_='foreignkey')
    op.drop_constraint(None, 'master_meters', type_='foreignkey')
    op.drop_constraint(None, 'master_meters', type_='foreignkey')
    op.drop_index(op.f('ix_master_meters_zone_id'), table_name='master_meters')
    op.drop_index(op.f('ix_master_meters_field_area_id'), table_name='master_meters')
    op.drop_index(op.f('ix_master_meters_area_id'), table_name='master_meters')
    op.drop_column('master_meters', 'field_area_id')
    op.drop_column('master_meters', 'area_id')
    op.drop_column('master_meters', 'zone_id')
    # ### end Alembic commands ###
