"""add officers

Revision ID: fbc248d9e8de
Revises: 9930249c84fe
Create Date: 2026-08-18 12:50:42.701569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc248d9e8de'
down_revision: Union[str, Sequence[str], None] = '9930249c84fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_code', sa.String(length=50), nullable=False),
    sa.Column('officer_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_email'), 'officers', ['email'], unique=True)
    op.create_index(op.f('ix_officers_officer_code'), 'officers', ['officer_code'], unique=True)
    op.create_index(op.f('ix_officers_phone'), 'officers', ['phone'], unique=True)
    op.create_index(op.f('ix_officers_role'), 'officers', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officers_role'), table_name='officers')
    op.drop_index(op.f('ix_officers_phone'), table_name='officers')
    op.drop_index(op.f('ix_officers_officer_code'), table_name='officers')
    op.drop_index(op.f('ix_officers_email'), table_name='officers')
    op.drop_table('officers')
    # ### end Alembic commands ###
